# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_Architecture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOS_Architecture

    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'ReachabilitySwift'
    pod 'NVActivityIndicatorView'
    pod 'IQKeyboardManagerSwift'
    pod 'DeviceKit'
    pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'

end
